"""initial schema

Revision ID: 58f29d25c05c
Revises:
Create Date: 2026-05-12 09:50:38.688407

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58f29d25c05c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("run_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rating", sa.String(length=16), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("investment_thesis", sa.Text(), nullable=True),
        sa.Column("price_target", sa.Float(), nullable=True),
        sa.Column("time_horizon", sa.String(length=64), nullable=True),
        sa.Column("llm_provider", sa.String(length=32), nullable=True),
        sa.Column("deep_model", sa.String(length=64), nullable=True),
        sa.Column("quick_model", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "trade_date", name="uq_ticker_date"),
    )
    op.create_index(op.f("ix_analyses_ticker"), "analyses", ["ticker"], unique=False)
    op.create_table(
        "analysis_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("market_report", sa.Text(), nullable=True),
        sa.Column("sentiment_report", sa.Text(), nullable=True),
        sa.Column("news_report", sa.Text(), nullable=True),
        sa.Column("fundamentals_report", sa.Text(), nullable=True),
        sa.Column("bull_history", sa.Text(), nullable=True),
        sa.Column("bear_history", sa.Text(), nullable=True),
        sa.Column("research_decision", sa.Text(), nullable=True),
        sa.Column("trader_plan", sa.Text(), nullable=True),
        sa.Column("risk_aggressive", sa.Text(), nullable=True),
        sa.Column("risk_conservative", sa.Text(), nullable=True),
        sa.Column("risk_neutral", sa.Text(), nullable=True),
        sa.Column("risk_decision", sa.Text(), nullable=True),
        sa.Column("full_state_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id"),
    )
    op.create_table(
        "analysis_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("queued_at", sa.DateTime(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=False),
        sa.Column("raw_return", sa.Float(), nullable=False),
        sa.Column("alpha_return", sa.Float(), nullable=False),
        sa.Column("holding_days", sa.Integer(), nullable=False),
        sa.Column("reflection", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcomes")
    op.drop_table("analysis_queue")
    op.drop_table("analysis_details")
    op.drop_index(op.f("ix_analyses_ticker"), table_name="analyses")
    op.drop_table("analyses")
    # ### end Alembic commands ###
